### ISSUE TITLE
Does not work on WSL2

### ISSUE THREAD

**Issue by genna87** [cobacdavid/dtv2#13]
I'm trying to run it on WSL2.

This command gives me an unexpected error.

`$ dtv2change -kbd white`

    Traceback (most recent call last):
      File "/home/user/.local/bin/dtv2change", line 179, in <module>
        change.apply_changes()
      File "/home/user/.local/bin/dtv2change", line 81, in apply_changes
        self.clavier.key_set(self.dico_touches)
      File "/home/user/.local/lib/python3.10/site-packages/dtv2/dtv2.py", line 435, in key_set
        self.__key_set(id_keys, rgb_colors)
      File "/home/user/.local/lib/python3.10/site-packages/dtv2/dtv2.py", line 405, in __key_set
        self.__apply_packets(packets)
      File "/home/user/.local/lib/python3.10/site-packages/dtv2/dtv2.py", line 275, in __apply_packets
        a = self.__write_device()
      File "/home/user/.local/lib/python3.10/site-packages/dtv2/dtv2.py", line 207, in __write_device
        a = self.dev.write(self.packet)
    AttributeError: 'NoneType' object has no attribute 'write'

**Comment by genna87** [comment]
On second thought this probably isn't a WSL2 issue, but something similar to #7.
I'm using a keyboard with the Italian layout (88 keys)

**Comment by cobacdavid** [comment]
Can you test those python3 lines in your Python console:
```python
>>> import hid
>>> hid.enumerate(0x416, 0xa0f8)
```

**Comment by genna87** [comment]
Empty array:

    []

**Comment by cobacdavid** [comment]
It seems the keyboard is not detected. Actually I do not know how WSL2 does to make USB devices available...

Edit: Maybe use [this method](https://www.lieselhughes.com/posts/tech/usb-hacking/connecting-usb-devices-to-wsl/) to enable the device.
